include $(GOROOT)/src/Make.inc

TARG=digestw_web
GOFILES=\
	web.go\
	../common/twitter.go\
	../common/model.go\
	../common/string.go\
	../common/http.go\
	../common/twitter2mongo.go

include $(GOROOT)/src/Make.cmd
